NAMESPACE_SUBJECT = "/subject"
NAMESPACE_OBJECT = "/object"

EVENT_CONNECT = "connect"
EVENT_DISCONNECT = "disconnect"
EVENT_START_STREAM = "startGoogleCloudStream"
EVENT_BINARY_AUDIO = "binaryAudioData"
EVENT_END_STREAM = "endGoogleCloudStream"
EVENT_SPEECH_DATA = "speechData"

KEY_LINEAR16 = "LINEAR16"
KEY_ENCODING = "encoding"
KEY_LANGUAGE_CODE = "languageCode"
KEY_SAMPLE_RATE_HERTZ = "sampleRateHertz"
KEY_TARGET_LANGUAGE = "targetLanguage"
KEY_INTERIM_RESULTS = "interimResults"
KEY_AUDIO = "audio"
KEY_DATA = "data"
KEY_IS_FINAL = "isFinal"
KEY_INPUT = "input"
KEY_TRANSLATED_TEXT = "translatedText"
KEY_DETECTED_SOURCE_LANGUAGE = "detectedSourceLanguage"
